services:
  hubble-chatbot-api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: hubble_chatbot_api
    container_name: hubble_chatbot_api
    ports:
      - "127.0.0.1:9001:8000"
    env_file:
      - ./.env
    environment:
      - CHATBOT_API_LOG_LEVEL=INFO
      - DB__HOST=chatbot_postgres
      - AWS_ENDPOINT_URL_S3=http://chatbot-localstack:4566
    volumes:
      - .:/app
    depends_on:
      - hubble-chatbot-postgres
      - hubble-chatbot-localstack

  hubble-chatbot-postgres:
    image: postgres:15-alpine
    container_name: hubble_chatbot_postgres
    environment:
      - POSTGRES_USER=${DB__USER}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
      - POSTGRES_DB=${DB__NAME}
    ports:
      - "127.0.0.1:5435:5432"

  hubble-chatbot-localstack:
    image: localstack/localstack
    container_name: hubble_chatbot_localstack
    environment:
      - DEBUG=0
      - SERVICES=s3
      - X_DEFAULT_REGION=us-east-1
    ports:
      - "127.0.0.1:4568:4566"
    volumes:
      - "./docker/localstack/init-resources.sh:/etc/localstack/init/ready.d/init-resources.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - ./.env

  hubble-redis:
    image: redis:latest
    container_name: hubble_chatbot_redis
    ports:
      - "${REDIS__PORT:-6379}:6379"
    command: >
      redis-server
      --requirepass "${REDIS__PASSWORD}"
    environment:
      REDIS_PASSWORD: ${REDIS__PASSWORD}
    volumes:
      - hubble_redis_data:/data
    env_file:
      - ./.env

volumes:
  hubble_redis_data:
